# =========================
# 301 redirect to Google
# =========================
[[redirects]]
  from = "/netlify/:anything"
  to = "https://www.google.com/search?q=:anything"
  status = 301
  force = true


# =========================
# Proxy redirect (status 200)
# =========================
[[redirects]]
  from = "/netlify-proxy/:anything"
  to = "https://www.google.com/search?q=:anything"
  status = 200
  force = true
